<?php
if ( ! defined( 'ABSPATH' ) ) exit;
add_settings_field(
  'dyptt-check-products-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-check-pagechack-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-check-position-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
// Taxos
add_settings_field(
  'dyptt-check-price-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-check-categories-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-check-tags-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-check-weight-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-check-dimensions-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-check-stock-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-check-sku-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-check-date-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-check-slug-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-check-featured-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-check-reviews-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-check-shippingclass-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);

// Taxos label check
add_settings_field(
  'dyptt-label-check-price-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-label-check-categories-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-label-check-tags-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-label-check-weight-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-label-check-dimensions-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-label-check-stock-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-label-check-sku-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-label-check-date-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-label-check-slug-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-label-check-featured-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-label-check-reviews-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-label-check-shippingclass-taxo-widget',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);

// Popup controls
// *** Price
add_settings_field(
  'dyptt-price-text',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-price-color',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-price-fontsize',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-price-fontfamilly',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
// *** categories
add_settings_field(
  'dyptt-categories-text',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-categories-color',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-categories-fontsize',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-categories-fontfamilly',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
// *** tags
add_settings_field(
  'dyptt-tags-text',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-tags-color',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-tags-fontsize',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-tags-fontfamilly',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
// *** weight
add_settings_field(
  'dyptt-weight-text',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-weight-color',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-weight-fontsize',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-weight-fontfamilly',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
// *** dimensions
add_settings_field(
  'dyptt-dimensions-text',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-dimensions-color',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-dimensions-fontsize',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-dimensions-fontfamilly',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
// *** stock
add_settings_field(
  'dyptt-stock-text',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-stock-color',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-stock-fontsize',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-stock-fontfamilly',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
// *** sku
add_settings_field(
  'dyptt-sku-text',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-sku-color',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-sku-fontsize',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-sku-fontfamilly',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
// *** date
add_settings_field(
  'dyptt-date-text',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-date-color',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-date-fontsize',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-date-fontfamilly',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
// *** slug
add_settings_field(
  'dyptt-slug-text',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-slug-color',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-slug-fontsize',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-slug-fontfamilly',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
// *** featured
add_settings_field(
  'dyptt-featured-text',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-featured-color',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-featured-fontsize',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-featured-fontfamilly',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
// *** reviews
add_settings_field(
  'dyptt-reviews-text',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-reviews-color',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-reviews-fontsize',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-reviews-fontfamilly',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
// *** shippingclass
add_settings_field(
  'dyptt-shippingclass-text',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-shippingclass-color',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-shippingclass-fontsize',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);
add_settings_field(
  'dyptt-shippingclass-fontfamilly',
  '',
  'dyptt_plugin_function_for_datas_callback',
  'dyptt-plugin-main-menu',
  'dyptt-plugin-switch-section'
);

// Register Settings all
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-check-products-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-check-pagechack-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-check-position-taxo-widget' 
);
// Taxos
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-check-price-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-check-categories-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-check-tags-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-check-weight-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-check-dimensions-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-check-stock-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-check-sku-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-check-date-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-check-slug-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-check-featured-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-check-reviews-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-check-shippingclass-taxo-widget' 
);

// Taxos label check
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-label-check-price-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-label-check-categories-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-label-check-tags-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-label-check-weight-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-label-check-dimensions-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-label-check-stock-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-label-check-sku-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-label-check-date-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-label-check-slug-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-label-check-featured-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-label-check-reviews-taxo-widget' 
);
register_setting( 
  'dyptt-plugin-settings', 
  'dyptt-label-check-shippingclass-taxo-widget' 
);

// Popup controls
// *** Price
register_setting(
  'dyptt-plugin-settings',
  'dyptt-price-text'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-price-color'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-price-fontsize'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-price-fontfamilly'
);
// *** categories
register_setting(
  'dyptt-plugin-settings',
  'dyptt-categories-text'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-categories-color'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-categories-fontsize'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-categories-fontfamilly'
);
// *** tags
register_setting(
  'dyptt-plugin-settings',
  'dyptt-tags-text'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-tags-color'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-tags-fontsize'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-tags-fontfamilly'
);
// *** weight
register_setting(
  'dyptt-plugin-settings',
  'dyptt-weight-text'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-weight-color'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-weight-fontsize'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-weight-fontfamilly'
);
// *** dimensions
register_setting(
  'dyptt-plugin-settings',
  'dyptt-dimensions-text'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-dimensions-color'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-dimensions-fontsize'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-dimensions-fontfamilly'
);
// *** stock
register_setting(
  'dyptt-plugin-settings',
  'dyptt-stock-text'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-stock-color'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-stock-fontsize'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-stock-fontfamilly'
);
// *** sku
register_setting(
  'dyptt-plugin-settings',
  'dyptt-sku-text'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-sku-color'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-sku-fontsize'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-sku-fontfamilly'
);
// *** date
register_setting(
  'dyptt-plugin-settings',
  'dyptt-date-text'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-date-color'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-date-fontsize'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-date-fontfamilly'
);
// *** slug
register_setting(
  'dyptt-plugin-settings',
  'dyptt-slug-text'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-slug-color'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-slug-fontsize'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-slug-fontfamilly'
);
// *** featured
register_setting(
  'dyptt-plugin-settings',
  'dyptt-featured-text'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-featured-color'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-featured-fontsize'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-featured-fontfamilly'
);
// *** reviews
register_setting(
  'dyptt-plugin-settings',
  'dyptt-reviews-text'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-reviews-color'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-reviews-fontsize'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-reviews-fontfamilly'
);
// *** shippingclass
register_setting(
  'dyptt-plugin-settings',
  'dyptt-shippingclass-text'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-shippingclass-color'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-shippingclass-fontsize'
);
register_setting(
  'dyptt-plugin-settings',
  'dyptt-shippingclass-fontfamilly'
);